# -*- coding: utf-8 -*-
"""ТЗ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FkF1U7kzHzPsOXjaqF8yrBhtyCIbQYky

"Завдання 1. Створити функцію, яка приймає два аргументи (число та ступінь), та повертає результат підняття числа до вказаної ступені"
"""

# перший спосіб
print(pow(3, 4))

# другий спосіб
def power(a, b):
  return a ** b

power(3, 4)

""""Завдання 2. Написати програму, яка виводить всі парні числа від 1 до 20."
"""

for x in range(1, 20):
  if x % 2 == 0:
    print(x)

""""Завдання 3. Створити список чисел від 1 до 10, та вивести його зворотньо."
"""

numbers = list(range(1, 10))
print(list(reversed(numbers)))

""""Завдання 4. Написати функцію, яка приймає рядок та повертає кількість унікальних символів у цьому рядку."
"""

def count_unique_chars(text):
    return len(set(text))

user_input = input("Введи рядок: ")
print("Кількість унікальних символів:", count_unique_chars(user_input))

"""Завдання 5. Перевернути массив використовуючи зворотню індексацію."""

array_ = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
reversed_list = array_[::-1]
print(reversed_list)

""""Завдання 6. Створити словник, який містить дані про книгу (назва, автор, рік видання) та вивести його вміст"
"""

book_data = {"title": "Adventures", "author": "Milano Perretini", "year": 1984}
print(book_data)

""""Завдання 7. Написати програму, яка обчислює суму перших 100 натуральних чисел"
"""

total = sum(range(1, 101))
print("Сума перших 100 натуральних чисел:", total)

"""Завдання 1. Створити DataFrame з двох списків (назва книги та автор) та вивести перші 5 рядків:"""

import pandas as pd

titles = ["Книга 1", "Книга 2", "Книга 3", "Книга 4", "Книга 5", "Книга 6", "Книга 7"]
authors = ["Автор A", "Автор B", "Автор C", "Автор D", "Автор E", "Автор F", "Автор G"]

books_data = pd.DataFrame({
    "Назва книги": titles,
    "Автор": authors
})

print(books_data.head())

"""Завдання 2. Завантажити даних з CSV-файлу та вивести статистику про числові колонки"""

df = pd.read_csv("taxis.csv")
print(df.describe())

""""Завдання 3. Вибрати лише рядки, де значення у колонці ""Оцінка"" більше 4"
"""

data = {
    "Студент": ["Студент 1", "Студент 2", "Студент 3", "Студент 4", "Студент 5", "Студент 6", "Студент 7"],
    "Оцінка": [4, 3, 4, 3, 5, 2, 5],
    "Назва книги": titles
}
df = pd.DataFrame(data)
print(df)

# Вибір рядків, де значення в колонці "Оцінка" більше 4
filtered_df = df[df["Оцінка"] > 4]
print(filtered_df)

"""Завдання 4. Об'єднати два DataFrames за спільними колонками та вивести результат"""

merged_df = pd.merge(df, books_data, on="Назва книги")
print(merged_df)

""""Завдання 5. Використати функцію apply для створення нового стовпця на основі умови - У вас є таблиця з оцінками студентів, і вам потрібно створити новий стовпець ""Grade"" на основі наступних критеріїв: A (90 і вище), B (80-89), C (менше 80). Дані:import pandas as pddata = {'Score': [85, 92, 78, 95, 88]}df = pd.DataFrame(data)"
"""

import pandas as pd

data = {'Score': [85, 92, 78, 95, 88]}
df = pd.DataFrame(data)

def assign_grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    else:
        return "C"

df["Grade"] = df["Score"].apply(assign_grade)

print(df)